tableextension 95102 NameBufferValue extends "Name/Value Buffer"
{
    fields
    {
        field(95100; "Google Drive ID"; Text[250])
        {
            Caption = 'Google Drive ID';
            DataClassification = CustomerContent;
        }
        field(95101; "Google Drive Parent ID"; Text[250])
        {
            Caption = 'Google Drive Parent ID';
            DataClassification = CustomerContent;
        }
    }
}
